# Generated by Django 4.2.8 on 2023-12-06 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeagueOf2Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Title')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
                ('player_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leagues_2p_p1', to=settings.AUTH_USER_MODEL, verbose_name='Player 1')),
                ('player_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leagues_2p_p2', to=settings.AUTH_USER_MODEL, verbose_name='Player 2')),
            ],
            options={
                'verbose_name': 'League of 2 Players',
                'verbose_name_plural': 'Leagues of 2 Players',
            },
        ),
        migrations.CreateModel(
            name='LeagueOf3Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Title')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
                ('player_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leagues_3p_p1', to=settings.AUTH_USER_MODEL, verbose_name='Player 1')),
                ('player_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leagues_3p_p2', to=settings.AUTH_USER_MODEL, verbose_name='Player 2')),
                ('player_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leagues_3p_p3', to=settings.AUTH_USER_MODEL, verbose_name='Player 3')),
            ],
            options={
                'verbose_name': 'League of 3 Players',
                'verbose_name_plural': 'Leagues of 3 Players',
            },
        ),
        migrations.CreateModel(
            name='LeagueOf4Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Title')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
                ('player_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leagues_4p_p1', to=settings.AUTH_USER_MODEL, verbose_name='Player 1')),
                ('player_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leagues_4p_p2', to=settings.AUTH_USER_MODEL, verbose_name='Player 2')),
                ('player_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leagues_4p_p3', to=settings.AUTH_USER_MODEL, verbose_name='Player 3')),
                ('player_4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leagues_4p_p4', to=settings.AUTH_USER_MODEL, verbose_name='Player 4')),
            ],
            options={
                'verbose_name': 'League of 4 Players',
                'verbose_name_plural': 'Leagues of 4 Players',
            },
        ),
        migrations.CreateModel(
            name='Result4Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played_at', models.DateField(verbose_name='Played at')),
                ('num_games', models.IntegerField(verbose_name='Number of games')),
                ('player_1_points', models.IntegerField(verbose_name='Points Player 1')),
                ('player_2_points', models.IntegerField(verbose_name='Points Player 2')),
                ('player_3_points', models.IntegerField(verbose_name='Points Player 3')),
                ('player_4_points', models.IntegerField(verbose_name='Points Player 4')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='core.leagueof4players', verbose_name='League')),
            ],
            options={
                'verbose_name': 'Result of a 4 Player game',
                'verbose_name_plural': 'Results of 4 Player games',
            },
        ),
        migrations.CreateModel(
            name='Result3Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played_at', models.DateField(verbose_name='Played at')),
                ('num_games', models.IntegerField(verbose_name='Number of games')),
                ('player_1_points', models.IntegerField(verbose_name='Points Player 1')),
                ('player_2_points', models.IntegerField(verbose_name='Points Player 2')),
                ('player_3_points', models.IntegerField(verbose_name='Points Player 3')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='core.leagueof3players', verbose_name='League')),
            ],
            options={
                'verbose_name': 'Result of a 3 Player game',
                'verbose_name_plural': 'Results of 3 Player games',
            },
        ),
        migrations.CreateModel(
            name='Result2Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played_at', models.DateField(verbose_name='Played at')),
                ('num_games', models.IntegerField(verbose_name='Number of games')),
                ('player_1_points', models.IntegerField(verbose_name='Points Player 1')),
                ('player_2_points', models.IntegerField(verbose_name='Points Player 2')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='core.leagueof2players', verbose_name='League')),
            ],
            options={
                'verbose_name': 'Result of a 2 Player game',
                'verbose_name_plural': 'Results of 2 Player games',
            },
        ),
    ]
