# Generated by Django 4.2.8 on 2023-12-05 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_resultthreeplayer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultFourPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played_at', models.DateField(verbose_name='Played at')),
                ('num_games', models.IntegerField(verbose_name='Number of games')),
                ('player_1_points', models.IntegerField(verbose_name='Points Player 1')),
                ('player_2_points', models.IntegerField(verbose_name='Points Player 2')),
                ('player_3_points', models.IntegerField(verbose_name='Points Player 3')),
                ('player_4_points', models.IntegerField(verbose_name='Points Player 4')),
                ('player_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results_four_player_1', to=settings.AUTH_USER_MODEL, verbose_name='Player 1')),
                ('player_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results_four_player_2', to=settings.AUTH_USER_MODEL, verbose_name='Player 2')),
                ('player_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results_four_player_3', to=settings.AUTH_USER_MODEL, verbose_name='Player 3')),
                ('player_4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results_four_player_4', to=settings.AUTH_USER_MODEL, verbose_name='Player 3')),
            ],
            options={
                'verbose_name': 'Result of a 4 Player game',
                'verbose_name_plural': 'Results of 4 Player games',
            },
        ),
    ]
