# Generated by Django 4.2.8 on 2024-02-13 16:01

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_leagueof4players_player_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextended',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=25, null=True, samples=None, verbose_name='Color'),
        ),
    ]
